/** Stable kebab slugs for every catalog course. Generated from live titles; bearings slug is locked. */

export const FLAGSHIP_BEARINGS_COURSE_ID = 'afb65829-8dee-4817-bb7b-aa03954fbef0';
export const FLAGSHIP_BEARINGS_SLUG = 'bearings-lubrication-alignment-fundamentals';
export const FLAGSHIP_ELECTRICAL_COURSE_ID = 'd944e6dd-5c67-4196-9943-8c3b18d962f7';
export const FLAGSHIP_ELECTRICAL_SLUG = 'motor-testing-with-megger-pi';

export type CourseSeoRecord = {
  id: string;
  slug: string;
  title: string;
  stage: 'mechanical' | 'electrical' | 'ie' | 'engineering';
  tier: 'free' | 'premium';
  description: string;
};

export const COURSE_SEO: CourseSeoRecord[] = [
  {
    id: "afb65829-8dee-4817-bb7b-aa03954fbef0",
    slug: "bearings-lubrication-alignment-fundamentals",
    title: "Bearings, Lubrication & Alignment Fundamentals",
    stage: "mechanical",
    tier: "free",
    description: "Master the fundamentals of rolling-element bearings, proper lubrication practices, and precision shaft alignment. Covers bearing selection, failure modes, lubricant chemistry, and laser alignment techniques used across rotating equipment in modern plants.",
  },
  {
    id: "a5764488-85c6-4f34-af92-b5eaa93ab2b1",
    slug: "plc-programming-best-practices-logix-style",
    title: "PLC Programming Best Practices (Logix-style)",
    stage: "engineering",
    tier: "premium",
    description: "Structured, maintainable PLC programming in a Logix-style environment. Covers tag naming, program organization, AOIs, and safety routines for industrial control.",
  },
  {
    id: "4f752341-8433-4d0f-bd90-fb3c4c9872b4",
    slug: "hart-transmitters-and-smart-instrumentation",
    title: "HART Transmitters & Smart Instrumentation",
    stage: "ie",
    tier: "premium",
    description: "Configure and troubleshoot HART smart transmitters using a handheld communicator. Covers loop integration, device calibration, and digital signal diagnostics for modern process instrumentation.",
  },
  {
    id: "2ad7d2f0-ec35-4553-b7a1-1fdb93f2f8bb",
    slug: "industrial-motor-control-circuits",
    title: "Industrial Motor Control Circuits",
    stage: "electrical",
    tier: "free",
    description: "Read and troubleshoot industrial motor control circuits from the line diagram to the starter. Covers NEMA and IEC contactors, overload protection, control transformers, and common control circuit faults.",
  },
  {
    id: "9a4e3263-3ead-4a8b-be5a-1df7d81da8af",
    slug: "system-architecture-and-network-design",
    title: "System Architecture & Network Design",
    stage: "engineering",
    tier: "premium",
    description: "Design robust industrial control system architectures. Covers controller selection, network segmentation, redundancy, and the Purdue model for OT security.",
  },
  {
    id: "119e761c-f930-4e39-8c7c-963d2c6ce1c0",
    slug: "3-phase-power-systems-and-troubleshooting",
    title: "3-Phase Power Systems & Troubleshooting",
    stage: "electrical",
    tier: "free",
    description: "Understand 3-phase power distribution in the plant, from the service entrance to the motor terminal box. Covers wye/delta, voltage and current unbalance, and phasing checks.",
  },
  {
    id: "0009a826-7db0-446d-99d5-c97e03f2c8ff",
    slug: "pump-and-mechanical-seal-maintenance",
    title: "Pump & Mechanical Seal Maintenance",
    stage: "mechanical",
    tier: "free",
    description: "Hands-on maintenance of centrifugal pumps and mechanical seals. Learn to identify cavitation, replace seals correctly, perform impeller clearance checks, and reduce MTTR on critical process pumps.",
  },
  {
    id: "9bc05085-a6e2-40ef-9056-afa3f273b2f4",
    slug: "control-valve-calibration-and-diagnostics",
    title: "Control Valve Calibration & Diagnostics",
    stage: "ie",
    tier: "premium",
    description: "Calibrate and diagnose control valves and their positioners. Covers stroke calibration, bench set, valve signature, and diagnosing stiction and hysteresis in service.",
  },
  {
    id: "79f10708-c531-41d9-813a-6e166836a274",
    slug: "vfd-fundamentals-parameterization",
    title: "VFD Fundamentals & Parameterization",
    stage: "electrical",
    tier: "free",
    description: "Variable frequency drives from the rectifier to the IGBT output. Learn to wire, start up, and parameterize a VFD, and to diagnose the most common drive faults.",
  },
  {
    id: "72b79e38-4066-4f97-a7b9-fe499177407f",
    slug: "reliability-engineering-and-predictive-maintenance-strategy",
    title: "Reliability Engineering & Predictive Maintenance Strategy",
    stage: "engineering",
    tier: "premium",
    description: "Build a reliability program from failure modes to predictive maintenance. Covers FMEA, Weibull analysis, condition monitoring, and KPIs like MTBF and OEE.",
  },
  {
    id: "e6064434-676e-4f50-97d4-d6ed1bf5f262",
    slug: "deltav-dcs-fundamentals-for-technicians",
    title: "DeltaV / DCS Fundamentals for Technicians",
    stage: "ie",
    tier: "premium",
    description: "Navigate a modern distributed control system from the technician perspective. Covers module hierarchy, control strategies, alarms, and troubleshooting on a DeltaV-style system.",
  },
  {
    id: "70c4ca50-ccdb-4179-a110-43879f5a4d9c",
    slug: "conveyor-and-drive-systems",
    title: "Conveyor & Drive Systems",
    stage: "mechanical",
    tier: "free",
    description: "Maintain belt, roller, and chain conveyors plus the gear drives and power transmission components behind them. Covers belt tracking, sprocket wear, gearbox inspection, and tensioning procedures.",
  },
  {
    id: "f371b00f-9440-436d-bd1d-0967359ad4b2",
    slug: "fieldbus-and-industrial-ethernet-troubleshooting",
    title: "Fieldbus & Industrial Ethernet Troubleshooting",
    stage: "ie",
    tier: "premium",
    description: "Troubleshoot Foundation Fieldbus H1 segments and industrial Ethernet networks. Covers segment sizing, terminators, MAC address issues, and managed switch diagnostics.",
  },
  {
    id: "0e30a966-4597-4d0d-9e55-2eaa0d6de8cc",
    slug: "precision-measurement-and-troubleshooting",
    title: "Precision Measurement & Troubleshooting",
    stage: "mechanical",
    tier: "free",
    description: "Use dial indicators, calipers, micrometers, and laser measurement tools to diagnose mechanical problems to thousandths of an inch. Includes runout, concentricity, and soft-foot checks.",
  },
  {
    id: "1de5e537-1fa1-4b8d-878a-ac287e114e48",
    slug: "advanced-motion-and-safety-systems",
    title: "Advanced Motion & Safety Systems",
    stage: "engineering",
    tier: "premium",
    description: "Integrated motion control and functional safety. Covers coordinated motion, safety PLCs, SIL determination, and safety function design to IEC 62061 / ISO 13849.",
  },
  {
    id: "d944e6dd-5c67-4196-9943-8c3b18d962f7",
    slug: "motor-testing-with-megger-pi",
    title: "Motor Testing with Megger & PI",
    stage: "electrical",
    tier: "free",
    description: "Insulation resistance testing and polarization index for motors and generators. Covers test voltages, interpretation, and trending for predictive maintenance.",
  },
  {
    id: "0eeb8bf6-b037-43a8-8cf3-ebf8bbd76a52",
    slug: "studio-5000-logix-system-architecture-deep-dive",
    title: "Studio 5000 / Logix System Architecture Deep Dive",
    stage: "engineering",
    tier: "premium",
    description: "Comprehensive guide to Rockwell Studio 5000 and Logix platform architecture. Covers project organization, tasks, programs, routines, UDTs, AOIs, I/O configuration, and best practices for scalable, maintainable PLC projects in process and discrete applications.",
  },
  {
    id: "5f2941a8-be3b-4d2f-8329-a3a8dd896e94",
    slug: "hydraulics-and-pneumatics-basics",
    title: "Hydraulics & Pneumatics Basics",
    stage: "mechanical",
    tier: "free",
    description: "Understand hydraulic and pneumatic systems from the reservoir to the actuator. Covers pumps, valves, accumulators, cylinders, common failures, and safe lockout practices for fluid power systems.",
  },
  {
    id: "693be544-0e16-4d9d-ba84-4f5783bf5a01",
    slug: "electrical-safety-and-arc-flash-awareness",
    title: "Electrical Safety & Arc Flash Awareness",
    stage: "electrical",
    tier: "free",
    description: "NFPA 70E-oriented electrical safety training. Covers energized work permits, PPE categories, approach boundaries, and lockout/tagout for electrical work.",
  },
  {
    id: "84c0f408-f819-491e-8e69-da832b1565b5",
    slug: "advanced-loop-tuning",
    title: "Advanced Loop Tuning",
    stage: "ie",
    tier: "premium",
    description: "Tune process control loops using proven methods. Covers Ziegler-Nichols, lambda tuning, and diagnosing common loop pathologies like stiction and integrator windup.",
  },
  {
    id: "706bfb6e-e6ae-41df-ba9a-6f4f89004d96",
    slug: "ethernet-ip-network-design-and-segmentation",
    title: "Ethernet/IP Network Design & Segmentation",
    stage: "engineering",
    tier: "premium",
    description: "Design and troubleshoot EtherNet/IP networks for industrial control systems. Covers topology, switch selection, IGMP snooping for multicast, QoS, DLR rings, and network segmentation per the Purdue model for reliable PLC-to-I/O communication.",
  },
  {
    id: "2dcd4cf8-c95a-4cc9-b9ef-a8162b8405f2",
    slug: "gearboxes-and-power-transmission",
    title: "Gearboxes & Power Transmission",
    stage: "mechanical",
    tier: "free",
    description: "Comprehensive coverage of industrial gearbox types, inspection, failure analysis, and maintenance. Covers helical, bevel, worm, and planetary gearboxes, oil selection, breather maintenance, and trending wear metals to predict failures before they happen.",
  },
  {
    id: "3bbff1c9-5685-4e62-b8cb-4c6193dd0d02",
    slug: "motor-starters-contactors-overload-relays",
    title: "Motor Starters, Contactors & Overload Relays",
    stage: "electrical",
    tier: "free",
    description: "Deep dive into motor starters, contactors, and overload relays for industrial applications. Covers NEMA vs IEC contactors, selection criteria, overload class selection, arc suppression, and troubleshooting contactor failures.",
  },
  {
    id: "3190e6c5-4dd9-49d5-b939-169f7b6cb34f",
    slug: "pressure-measurement-and-transmitters",
    title: "Pressure Measurement & Transmitters",
    stage: "ie",
    tier: "premium",
    description: "Configure, calibrate, and troubleshoot industrial pressure transmitters. Covers pressure types (gauge, absolute, differential), diaphragm seals, impulse lines, zero suppression/elevation, and 4-20 mA loop integration for process pressure measurement.",
  },
  {
    id: "0f4bd1c1-bf01-4b0a-a903-4ca4804234fd",
    slug: "fans-blowers-and-air-handling-systems",
    title: "Fans, Blowers & Air Handling Systems",
    stage: "mechanical",
    tier: "free",
    description: "Maintain industrial fans, blowers, and air handling units. Covers fan types (centrifugal, axial), bearing arrangements, vibration diagnosis, impeller inspection, and performance testing for HVAC and process air systems.",
  },
  {
    id: "db57e4a5-c723-4184-ba3c-9f1b59ddb3df",
    slug: "temperature-measurement-rtd-thermocouple-infrared",
    title: "Temperature Measurement (RTD, Thermocouple, Infrared)",
    stage: "ie",
    tier: "premium",
    description: "Industrial temperature measurement fundamentals. Covers RTD vs thermocouple selection, 2-wire/3-wire/4-wire RTD circuits, thermocouple types and cold junction compensation, and infrared pyrometry for surface and process temperature.",
  },
  {
    id: "e7d34d85-de0c-4b75-a556-c76c094e3e0c",
    slug: "ot-cybersecurity-fundamentals-for-industrial-systems",
    title: "OT Cybersecurity Fundamentals for Industrial Systems",
    stage: "engineering",
    tier: "premium",
    description: "Operational technology (OT) cybersecurity for industrial control systems. Covers the Purdue model, IEC 62443 zones, risk assessment, patching strategies, network segmentation, and incident response for PLC and SCADA systems.",
  },
  {
    id: "6b276d7a-bc49-4613-a284-4fe7cfff4729",
    slug: "control-transformers-and-24v-control-circuits",
    title: "Control Transformers & 24V Control Circuits",
    stage: "electrical",
    tier: "free",
    description: "Design and troubleshoot 24V control circuits powered by step-down transformers. Covers transformer sizing, fuse selection, inrush, voltage drop, and common control circuit faults in industrial panels.",
  },
  {
    id: "1fecb273-2d8e-469a-8dda-a497307c4337",
    slug: "grounding-bonding-and-equipment-grounding-conductors",
    title: "Grounding, Bonding & Equipment Grounding Conductors",
    stage: "electrical",
    tier: "free",
    description: "Industrial grounding and bonding per NEC Article 250. Covers grounding electrode systems, equipment grounding conductors, bonding jumpers, ground fault current paths, and testing ground resistance.",
  },
  {
    id: "750f5dfb-d2e4-4adc-8dba-a0f6db71df86",
    slug: "industrial-couplings-keys-and-shafts",
    title: "Industrial Couplings, Keys & Shafts",
    stage: "mechanical",
    tier: "free",
    description: "Select, install, and maintain industrial couplings and shaft connections. Covers gear, grid, elastomeric, and disc couplings, key sizing, shaft repair, and coupling balance for reliable power transmission.",
  },
  {
    id: "0aa4a576-58a3-4fc2-aeeb-fbf361a017bb",
    slug: "functional-safety-iso-13849-and-iec-61511",
    title: "Functional Safety (ISO 13849 & IEC 61511)",
    stage: "engineering",
    tier: "premium",
    description: "Functional safety engineering for machinery and process systems. Covers ISO 13849 (machinery safety) performance levels, IEC 61511 (process SIS) SIL verification, safety function design, validation, and the relationship between the two standards.",
  },
  {
    id: "cc2fd161-3adb-418a-8d19-6527c13205f5",
    slug: "flow-measurement-technologies",
    title: "Flow Measurement Technologies",
    stage: "ie",
    tier: "premium",
    description: "Industrial flow measurement technologies and their application. Covers differential pressure (orifice, venturi), electromagnetic, vortex, Coriolis mass, and ultrasonic flow meters with selection criteria and troubleshooting.",
  },
  {
    id: "0383ad44-a771-4e46-b3e6-482b89367304",
    slug: "commissioning-startup-and-project-execution",
    title: "Commissioning, Startup & Project Execution",
    stage: "engineering",
    tier: "premium",
    description: "Systematic commissioning and startup of industrial control systems. Covers the commissioning plan, FAT/SAT, I/O checkout, loop checks, functional testing, punch list management, and handover to operations for a successful project startup.",
  },
  {
    id: "57d849a9-085d-4648-9b88-dd9dc6d032b7",
    slug: "level-measurement-radar-ultrasonic-differential",
    title: "Level Measurement (Radar, Ultrasonic, Differential)",
    stage: "ie",
    tier: "premium",
    description: "Industrial level measurement technologies. Covers differential pressure, ultrasonic, radar (FMCW and pulse), guided wave radar, capacitance, and hydrostatic level measurement with application selection and troubleshooting.",
  },
  {
    id: "bd4b0c33-6ddc-4c9e-9cdb-de444ee86e70",
    slug: "conduit-cable-tray-and-industrial-wiring-methods",
    title: "Conduit, Cable Tray & Industrial Wiring Methods",
    stage: "electrical",
    tier: "free",
    description: "Industrial wiring methods including rigid conduit, EMT, cable tray, and tray cable. Covers conduit bending, fill calculations, cable tray fill rules, and NEC Chapter 3 requirements for industrial installations.",
  },
  {
    id: "5381eb44-655a-404e-a2b5-08f811cff313",
    slug: "vibration-analysis-fundamentals",
    title: "Vibration Analysis Fundamentals",
    stage: "mechanical",
    tier: "free",
    description: "Introduction to vibration analysis for predictive maintenance. Covers sensor placement, frequency spectra, diagnosing imbalance, misalignment, looseness, and bearing defects from vibration signatures.",
  },
  {
    id: "396fd9ac-00d4-4907-8c21-8648a564a5c5",
    slug: "process-analyzers-and-sample-conditioning-systems",
    title: "Process Analyzers & Sample Conditioning Systems",
    stage: "ie",
    tier: "premium",
    description: "Maintain process analyzers (pH, ORP, conductivity, oxygen, gas chromatograph) and their sample conditioning systems. Covers probe selection, calibration, sample system design, and common analyzer faults.",
  },
  {
    id: "0b5c9254-b2ae-4b0f-b560-9136a5489cb5",
    slug: "thermography-for-mechanical-maintenance",
    title: "Thermography for Mechanical Maintenance",
    stage: "mechanical",
    tier: "free",
    description: "Use infrared thermography to detect mechanical problems before failure. Covers bearing overheating, coupling heat generation, steam trap diagnosis, electrical hot spots, and reporting best practices.",
  },
  {
    id: "2c007191-4099-4301-8465-5abd1d65ec1a",
    slug: "energy-management-and-efficient-drive-systems",
    title: "Energy Management & Efficient Drive Systems",
    stage: "engineering",
    tier: "premium",
    description: "Industrial energy management and drive system optimization. Covers motor efficiency classes (IE1-IE4), VFD energy savings, demand management, power factor correction, and ISO 50001 energy management system implementation.",
  },
  {
    id: "5d8324bd-3f8c-4f5b-b841-9c7a5dcfe76f",
    slug: "electrical-troubleshooting-methodology",
    title: "Electrical Troubleshooting Methodology",
    stage: "electrical",
    tier: "free",
    description: "Systematic approach to electrical troubleshooting in industrial environments. Covers the half-split method, voltage drop testing, current measurement, and building a diagnostic decision tree for fast fault isolation.",
  },
  {
    id: "03374f8a-369f-4689-8ec1-bbfc416d93bc",
    slug: "ultrasound-and-acoustic-lubrication",
    title: "Ultrasound & Acoustic Lubrication",
    stage: "mechanical",
    tier: "free",
    description: "Acoustic ultrasound inspection for bearing lubrication and leak detection. Covers ultrasound gun operation, bearing greasing by sound, steam trap testing, and electrical corona detection.",
  },
  {
    id: "e0739ab4-c11f-4c2e-b861-7b246c0eca5c",
    slug: "advanced-plc-programming-patterns-and-standards",
    title: "Advanced PLC Programming Patterns & Standards",
    stage: "engineering",
    tier: "premium",
    description: "Advanced PLC programming patterns for complex industrial applications. Covers state machines, sequencers, modular programming, IEC 61131-3 languages, and design patterns for batch, packaging, and process control.",
  },
  {
    id: "cf00e64c-d129-4202-ba54-e57d14c78184",
    slug: "soft-starters-and-reduced-voltage-starting",
    title: "Soft Starters & Reduced Voltage Starting",
    stage: "electrical",
    tier: "free",
    description: "Reduced voltage starting methods for large motors. Covers autotransformer, star-delta, and solid-state soft starters, starting torque, current limiting, and selecting the right method for the load.",
  },
  {
    id: "28e0e1c4-4c76-4e34-8c39-f3bd3f77d8cf",
    slug: "smart-valve-positioners-and-digital-feedback",
    title: "Smart Valve Positioners & Digital Feedback",
    stage: "ie",
    tier: "premium",
    description: "Configure and troubleshoot smart digital valve positioners. Covers HART and Foundation Fieldbus positioners, partial stroke testing, valve signature diagnostics, and integration with asset management systems.",
  },
  {
    id: "e4995bd0-845e-4571-8ce5-b01d7e401a38",
    slug: "safety-instrumented-systems-sis-fundamentals",
    title: "Safety Instrumented Systems (SIS) Fundamentals",
    stage: "ie",
    tier: "premium",
    description: "Introduction to Safety Instrumented Systems per IEC 61511. Covers SIS architecture, SIL verification, proof testing, bypass management, and the relationship between BPCS and SIS in process safety.",
  },
  {
    id: "0a1cb572-be55-4d56-92ce-73ae70ece9ad",
    slug: "rigging-lifting-and-material-handling",
    title: "Rigging, Lifting & Material Handling",
    stage: "mechanical",
    tier: "free",
    description: "Safe rigging and lifting practices for maintenance work. Covers sling selection, load calculation, crane signals, rigging hardware inspection, and critical lift planning for plant equipment moves.",
  },
  {
    id: "66b92839-3d47-48b0-bd5b-021405ad905c",
    slug: "industrial-panel-building-and-layout",
    title: "Industrial Panel Building & Layout",
    stage: "electrical",
    tier: "free",
    description: "Build and wire industrial control panels per NEC and UL 508A. Covers component placement, wire sizing, bundling, labeling, door interlocks, and panel inspection for compliance and maintainability.",
  },
  {
    id: "4044ddc8-440c-4f70-865e-30f6fe5beba5",
    slug: "motion-control-and-servo-systems",
    title: "Motion Control & Servo Systems",
    stage: "engineering",
    tier: "premium",
    description: "Industrial motion control and servo drive systems. Covers servo motor theory, tuning, coordinated motion, camming, gearing, and safety-rated motion functions for high-speed packaging and manufacturing applications.",
  },
  {
    id: "8fecbf82-7658-4486-9af8-f1503c3afbb2",
    slug: "ups-systems-batteries-and-backup-power",
    title: "UPS Systems, Batteries & Backup Power",
    stage: "electrical",
    tier: "free",
    description: "Maintain uninterruptible power supplies and battery systems for critical industrial loads. Covers UPS topologies, battery types, capacity testing, battery room safety, and preventive maintenance.",
  },
  {
    id: "8a6772f4-6a1f-4578-9cce-3ed659e9e201",
    slug: "machine-guarding-and-mechanical-loto",
    title: "Machine Guarding & Mechanical LOTO",
    stage: "mechanical",
    tier: "free",
    description: "Machine guarding standards and mechanical lockout/tagout procedures. Covers guard types, interlock systems, OSHA 1910.212, energy isolation for mechanical systems, and group LOTO for maintenance.",
  },
  {
    id: "b682b986-f6a1-4849-b1bb-d969a8ace56f",
    slug: "industrial-networking-managed-switches-vlans-qos",
    title: "Industrial Networking (Managed Switches, VLANs, QoS)",
    stage: "engineering",
    tier: "premium",
    description: "Industrial network design with managed switches. Covers VLAN segmentation, trunking, Spanning Tree (RSTP/MSTP), QoS prioritization, port security, and network monitoring for resilient industrial Ethernet infrastructure.",
  },
  {
    id: "ae4fb6b4-3a1f-403e-abc4-5c5e51acccd0",
    slug: "calibration-management-and-metrology",
    title: "Calibration Management & Metrology",
    stage: "ie",
    tier: "premium",
    description: "Build and maintain a calibration program for process instrumentation. Covers calibration intervals, traceability, uncertainty, as-found/as-left data, and managing a calibration system per ISA and ISO 17025 principles.",
  },
  {
    id: "7760c37a-95dc-4f23-91f6-aa7fd793ef04",
    slug: "hazardous-location-electrical-installations",
    title: "Hazardous Location Electrical Installations",
    stage: "electrical",
    tier: "free",
    description: "Electrical installations in hazardous (classified) locations per NEC Articles 500-504. Covers Class I/II/III, Division/Zone systems, explosionproof equipment, intrinsic safety, and sealing requirements.",
  },
  {
    id: "5d21f6da-0b87-40ab-b773-9b0b9d36ea39",
    slug: "centralized-and-automated-lubrication-systems",
    title: "Centralized & Automated Lubrication Systems",
    stage: "mechanical",
    tier: "free",
    description: "Design, install, and maintain centralized and automatic lubrication systems. Covers series-progressive, dual-line, and single-line systems, pump sizing, divider block operation, and troubleshooting flow issues.",
  },
  {
    id: "1aa5ea8a-1678-4dab-841e-1e1198d3bcd5",
    slug: "alarm-management-and-rationalization",
    title: "Alarm Management & Rationalization",
    stage: "engineering",
    tier: "premium",
    description: "Industrial alarm management per ISA 18.2. Covers alarm philosophy, rationalization, prioritization, nuisance alarm reduction, alarm shelving, and KPI monitoring for a manageable, actionable alarm system.",
  },
  {
    id: "955fe917-1db9-4a6d-962d-212202b20c00",
    slug: "wireless-instrumentation-and-remote-i-o",
    title: "Wireless Instrumentation & Remote I/O",
    stage: "ie",
    tier: "premium",
    description: "Deploy and maintain wireless instrumentation networks (ISA 100, WirelessHART) and remote I/O systems. Covers network design, gateway configuration, battery life management, and troubleshooting wireless links.",
  },
  {
    id: "db5d9e5b-633e-4c74-be17-e8cba8b18de3",
    slug: "reliability-centered-maintenance-strategy",
    title: "Reliability Centered Maintenance Strategy",
    stage: "engineering",
    tier: "premium",
    description: "Implement Reliability Centered Maintenance (RCM) for industrial assets. Covers FMEA, failure consequence analysis, task selection, and building a defensible maintenance program that balances cost, risk, and performance.",
  },
  {
    id: "c5fc85da-2d46-48e9-863d-aa79edc630d4",
    slug: "motor-protection-and-overcurrent-devices",
    title: "Motor Protection & Overcurrent Devices",
    stage: "electrical",
    tier: "free",
    description: "Motor protection devices including fuses, circuit breakers, MCPs, and electronic motor protection relays. Covers coordination, short-circuit protection, overload protection, and NEC 430 requirements.",
  },
  {
    id: "d81dce37-330c-49fe-8e82-97ff82f10952",
    slug: "welding-and-fabrication-for-maintenance-technicians",
    title: "Welding & Fabrication for Maintenance Technicians",
    stage: "mechanical",
    tier: "free",
    description: "Practical welding and fabrication skills for maintenance. Covers SMAW, GMAW, and GTAW basics, joint preparation, distortion control, and repair welding of shafts, brackets, and structural members.",
  },
  {
    id: "8eb64ec4-e524-4981-8b69-320bb9001de3",
    slug: "profibus-profinet-and-field-device-networks",
    title: "PROFIBUS, PROFINET & Field Device Networks",
    stage: "ie",
    tier: "premium",
    description: "Configure and troubleshoot PROFIBUS DP/PA and PROFINET networks. Covers topology, addressing, GSD files, diagnostic tools, and common network faults in industrial process and discrete applications.",
  },
  {
    id: "68e083a2-f156-4c9e-8093-56b508fd1e6a",
    slug: "digital-transformation-and-iiot-fundamentals-for-maintenance",
    title: "Digital Transformation & IIoT Fundamentals for Maintenance",
    stage: "engineering",
    tier: "premium",
    description: "Industrial IoT (IIoT) and digital transformation for maintenance organizations. Covers edge computing, cloud platforms, data architecture, predictive analytics, and building a business case for IIoT deployment in a maintenance context.",
  },
  {
    id: "24cc85fc-6e58-4100-a329-198581217cb9",
    slug: "chain-and-belt-drive-systems-advanced",
    title: "Chain & Belt Drive Systems Advanced",
    stage: "mechanical",
    tier: "free",
    description: "Advanced chain and belt drive maintenance. Covers multiple-chain drives, tensioning methods, sheave alignment, toothed belt timing, and diagnosing premature failure patterns in power transmission drives.",
  },
  {
    id: "c6adddfe-deb2-489d-9b23-a3e15631cf44",
    slug: "vfd-installation-commissioning",
    title: "Variable Frequency Drive Installation & Commissioning",
    stage: "electrical",
    tier: "free",
    description: "Practical VFD installation and commissioning beyond parameterization. Covers wiring, EMC considerations, motor cable selection, control wiring, startup procedure, and hand-off to operations.",
  },
  {
    id: "f61036ab-8ede-4887-954d-a7891522c43c",
    slug: "hart-advanced-diagnostics-and-device-management",
    title: "HART Advanced Diagnostics & Device Management",
    stage: "ie",
    tier: "premium",
    description: "Advanced HART diagnostics and asset management using a HART gateway or fieldbus coupler. Covers NAMUR NE 107 status signals, device alerts, predictive diagnostics, and integration with CMMS for maintenance workflow.",
  },
  {
    id: "93213ae9-c1d8-46d2-b8d7-a14bc35c85a8",
    slug: "electrical-prints-schematics-ladder-diagrams",
    title: "Electrical Prints, Schematics & Ladder Diagrams",
    stage: "electrical",
    tier: "free",
    description: "Read and interpret industrial electrical drawings. Covers one-line diagrams, ladder logic schematics, wiring diagrams, terminal block drawings, and cross-referencing between documents for troubleshooting.",
  },
  {
    id: "f08747c1-fc26-41e0-b2e2-6116986d895e",
    slug: "control-loop-performance-monitoring",
    title: "Control Loop Performance Monitoring",
    stage: "ie",
    tier: "premium",
    description: "Monitor and diagnose control loop performance using statistical and frequency-domain methods. Covers oscillation detection, stiction diagnosis, performance indices, and prioritizing loop maintenance for maximum impact.",
  },
  {
    id: "a1ac3800-1bca-4d6f-aa9f-557f856e7975",
    slug: "compressors-and-compressed-air-systems",
    title: "Compressors & Compressed Air Systems",
    stage: "mechanical",
    tier: "free",
    description: "Maintain industrial air compressors and compressed air systems. Covers rotary screw, reciprocating, and centrifugal compressors, air dryer selection, leak surveying, and system efficiency optimization.",
  },
  {
    id: "0ece2819-7467-4d79-96e9-b6ba24b8268e",
    slug: "heat-exchangers-and-cooling-systems",
    title: "Heat Exchangers & Cooling Systems",
    stage: "mechanical",
    tier: "free",
    description: "Maintain shell-and-tube, plate, and air-cooled heat exchangers. Covers tube cleaning, gasket replacement, fouling diagnosis, cooling tower water treatment, and thermal performance testing.",
  },
  {
    id: "0e42c42b-a532-41c9-a1c7-3589d864118c",
    slug: "lighting-systems-ballasts-and-led-retrofits",
    title: "Lighting Systems, Ballasts & LED Retrofits",
    stage: "electrical",
    tier: "free",
    description: "Industrial lighting maintenance and LED retrofit. Covers HID, fluorescent, and LED systems, ballast replacement, photometric considerations, and energy savings calculations for retrofit projects.",
  },
  {
    id: "4f524576-9dd7-422d-b5db-3aaadd9d91b0",
    slug: "instrument-installation-practices-and-best-practices",
    title: "Instrument Installation Practices & Best Practices",
    stage: "ie",
    tier: "premium",
    description: "Proper instrument installation per ISA and PIP standards. Covers impulse line routing, tubing and fittings, thermowell installation, grounding, lightning protection, and commissioning best practices for reliable measurement.",
  },
  {
    id: "c1305e87-e2e7-4380-950b-d0d0f8d14ba0",
    slug: "conveyor-troubleshooting-and-repair",
    title: "Conveyor Troubleshooting & Repair",
    stage: "mechanical",
    tier: "free",
    description: "Systematic troubleshooting of conveyor systems in production environments. Covers belt splice repair, roller replacement, drive diagnostics, take-up adjustment, and minimizing downtime during conveyor failures.",
  },
  {
    id: "6efca302-7ab1-44d2-aa5b-9e074a6d09f7",
    slug: "power-quality-basics",
    title: "Power Quality Basics",
    stage: "electrical",
    tier: "free",
    description: "Fundamentals of power quality in industrial facilities. Covers harmonics, voltage sags, swells, flicker, power factor, IEEE 519 limits, and mitigation strategies using filters and correction equipment.",
  },
  {
    id: "3c179fe9-62e6-4cad-85db-bb124cde7e69",
    slug: "temporary-power-and-construction-electrical",
    title: "Temporary Power & Construction Electrical",
    stage: "electrical",
    tier: "free",
    description: "Safe temporary power distribution for construction and maintenance. Covers GFCI requirements, temporary wiring rules, generator sizing, spider boxes, and OSHA 1926 Subpart K electrical safety.",
  },
  {
    id: "894cdeee-dc44-4d67-85d4-767e680d94c2",
    slug: "precision-maintenance-practices",
    title: "Precision Maintenance Practices",
    stage: "mechanical",
    tier: "free",
    description: "Precision maintenance methodology covering soft foot correction, pipe strain elimination, thermal growth compensation, and the tools and procedures that achieve machinery installation to specification.",
  },
  {
    id: "73230aa4-0e1c-41c4-912e-a0fec5f9dfaf",
    slug: "electrical-safety-programs-and-nfpa-70e-application",
    title: "Electrical Safety Programs & NFPA 70E Application",
    stage: "electrical",
    tier: "free",
    description: "Building and implementing an electrical safety program per NFPA 70E and OSHA. Covers the safety program elements, job briefings, energized work permits, audit requirements, and incident investigation.",
  },
  {
    id: "6f9c7344-6975-4b51-8269-613409683110",
    slug: "mechanical-seals-advanced-diagnostics",
    title: "Mechanical Seals Advanced Diagnostics",
    stage: "mechanical",
    tier: "free",
    description: "Advanced mechanical seal troubleshooting and failure analysis. Covers seal face materials, flush plans (API 682), barrier fluid systems, dry gas seals, and root cause analysis of seal failures.",
  },
  {
    id: "5b3f8d01-c2af-479c-a180-d5b1f87a4aaf",
    slug: "rotating-equipment-reliability-fundamentals",
    title: "Rotating Equipment Reliability Fundamentals",
    stage: "mechanical",
    tier: "free",
    description: "Build a reliability-centered approach to rotating equipment. Covers failure mode identification, condition monitoring strategy, criticality analysis, and aligning maintenance tasks to failure patterns.",
  },
  {
    id: "9bf71c94-4361-4322-988a-1650bc058037",
    slug: "testing-and-commissioning-of-electrical-equipment",
    title: "Testing & Commissioning of Electrical Equipment",
    stage: "electrical",
    tier: "free",
    description: "Acceptance testing and commissioning of electrical equipment. Covers insulation resistance, contact resistance, transformer turns ratio, primary injection, and NETA acceptance testing standards.",
  },
];

export const COURSE_SLUG_TO_ID: Record<string, string> = Object.fromEntries(
  COURSE_SEO.map((c) => [c.slug, c.id]),
);

export const COURSE_ID_TO_SLUG: Record<string, string> = Object.fromEntries(
  COURSE_SEO.map((c) => [c.id, c.slug]),
);

export const COURSE_SEO_BY_ID: Record<string, CourseSeoRecord> = Object.fromEntries(
  COURSE_SEO.map((c) => [c.id, c]),
);

const COURSE_SLUG_ALIASES: Record<string, string> = {
  'motor-testing-with-megger-and-pi': FLAGSHIP_ELECTRICAL_COURSE_ID,
  'vfd-fundamentals-and-parameterization': '79f10708-c531-41d9-813a-6e166836a274',
  'motor-starters-contactors-and-overload-relays': '3bbff1c9-5685-4e62-b8cb-4c6193dd0d02',
  'variable-frequency-drive-installation-and-commissioning': 'c6adddfe-deb2-489d-9b23-a3e15631cf44',
  'electrical-prints-schematics-and-ladder-diagrams': '93213ae9-c1d8-46d2-b8d7-a14bc35c85a8',
};

export function slugToCourseId(slug: string): string | undefined {
  const key = decodeURIComponent(slug || '').trim().toLowerCase();
  return COURSE_SLUG_TO_ID[key] ?? COURSE_SLUG_ALIASES[key];
}

export function courseIdToSlug(courseId: string): string | undefined {
  const id = (courseId || '').trim();
  return COURSE_ID_TO_SLUG[id] ?? COURSE_ID_TO_SLUG[id.toLowerCase()];
}

export function prettyCoursePath(courseId: string): string | undefined {
  const slug = courseIdToSlug(courseId);
  return slug ? `/courses/${slug}` : undefined;
}

export function isFlagshipBearingsCourse(courseId: string): boolean {
  return (courseId || '').trim().toLowerCase() === FLAGSHIP_BEARINGS_COURSE_ID;
}

export function isFlagshipElectricalCourse(courseId: string): boolean {
  return (courseId || '').trim().toLowerCase() === FLAGSHIP_ELECTRICAL_COURSE_ID;
}

export function titleToKebabSlug(title: string): string {
  const s = (title || '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  return s || 'course';
}
