import type { GameBlueprint } from './types';

export const COURSE_ID = 'afb65829-8dee-4817-bb7b-aa03954fbef0';

export const COURSE_TITLE = 'Bearings, Lubrication & Alignment Fundamentals';

export const GAME_SET: GameBlueprint[] = [
  {
    id: 'g1-crib-call',
    gameKey: 'g1-crib-call',
    number: 1,
    title: 'Crib Call: Right Bearing, Right Machine',
    shortTitle: 'Crib Call',
    level: 'foundational',
    summary: 'Drag-and-drop matching bearing family to machine.',
    implemented: true,
  },
  {
    id: 'g2-spall-or-smear',
    gameKey: 'g2-spall-or-smear',
    number: 2,
    title: 'Spall or Smear: Failure Mode ID',
    shortTitle: 'Spall or Smear',
    level: 'foundational',
    summary: 'Matching and identification of failure evidence (spalling, brinelling, smearing, false brinell, lubricant starve, corrosion).',
    implemented: true,
  },
  {
    id: 'g3-grease-or-oil',
    gameKey: 'g3-grease-or-oil',
    number: 3,
    title: 'Grease or Oil: Lube Call',
    shortTitle: 'Grease or Oil',
    level: 'foundational',
    summary: 'Decision tree for NLGI, oil vs grease, and viscosity for speed and temperature.',
    implemented: false,
  },
  {
    id: 'g4-fit-and-clearance',
    gameKey: 'g4-fit-and-clearance',
    number: 4,
    title: 'Fit and Clearance Board',
    shortTitle: 'Fit and Clearance',
    level: 'intermediate',
    summary: 'Drag shaft and housing fits (k5, m6, H7, C3) onto a 1800 RPM pump motor.',
    implemented: false,
  },
  {
    id: 'g5-soft-foot',
    gameKey: 'g5-soft-foot',
    number: 5,
    title: 'Soft Foot Before You Shoot Laser',
    shortTitle: 'Soft Foot',
    level: 'intermediate',
    summary: 'Sequence of operations: loosen, indicator, shim, recheck before alignment.',
    implemented: false,
  },
  {
    id: 'g6-rim-face-laser',
    gameKey: 'g6-rim-face-laser',
    number: 6,
    title: 'Rim and Face vs Dual Laser',
    shortTitle: 'Rim and Face',
    level: 'intermediate',
    summary: 'Interpret two sets of readings and pick the move (near/far, vertical/horizontal).',
    implemented: false,
  },
  {
    id: 'g7-thermal-growth',
    gameKey: 'g7-thermal-growth',
    number: 7,
    title: 'Thermal Growth Offset',
    shortTitle: 'Thermal Growth',
    level: 'intermediate',
    summary: 'Calculate and apply hot offset for a steam pump. Wrong sign fails.',
    implemented: false,
  },
  {
    id: 'g8-hot-bearing',
    gameKey: 'g8-hot-bearing',
    number: 8,
    title: 'Hot Bearing at 2 AM',
    shortTitle: 'Hot Bearing',
    level: 'advanced',
    summary: 'Fault tree: 210F DE bearing, 40F rise in 20 min. Choose tests (temp gun, stethoscope, amp, lube, alignment) in order. Wrong first test wastes a life.',
    implemented: false,
  },
  {
    id: 'g9-coupling-walk',
    gameKey: 'g9-coupling-walk',
    number: 9,
    title: 'Coupling Walk and Thrust',
    shortTitle: 'Coupling Walk',
    level: 'advanced',
    summary: 'Multi-system: angular misalignment plus thrust bearing distress plus oil level.',
    implemented: false,
  },
  {
    id: 'g10-train-alignment',
    gameKey: 'g10-train-alignment',
    number: 10,
    title: 'Train Alignment Under Time',
    shortTitle: 'Train Alignment',
    level: 'advanced',
    summary: 'Motor-coupling-pump-pipe strain LOTO plus sequence plus live feedback.',
    implemented: false,
  },
];
